version: '3'

services:
  postgres:
   image: postgres:14.1-alpine
   ports:
     - 5432:5432
   environment:
     - POSTGRES_USER=postgres 
     - POSTGRES_PASSWORD=postgres 
   volumes:
     - .data/postgres:/var/lib/postgresql/data 
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 10
  redis:
    image: redis:alpine
    volumes:
      - .data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  xscan-node: 
      image: quay.io/darwinia-network/xquery:sha-47014b1
      ports:
        - 8001:8001
      restart: always 
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
      environment:
        REDIS_PORT: 6379
        REDIS_HOST: redis 
        REDIS_DB: 0
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_DATABASE: postgres
        DB_HOST: postgres
        DB_PORT: 5432
        DATABASE_URL: "postgresql://postgres:postgres@postgres/postgres?schema=public"
      volumes:
        - ./:/app
      command:
        - --app=/app 
        - --port=8001
        - --monitor=true
         
         

        
        

   
