
name: example
version: 0.0.1
dbSchema:
   kind: Prisma
   file: ./prisma/schema.prisma
   migrateVersionName: init

dataSource:
  handlers:
    - file: ./src/dataSource/crabParachain.ts
    - file: ./src/dataSource/pangoroAccepted.ts
   
queueHandlers:
   handlers: 
    - file: ./src/handlers/pangoroDelivered.ts
    - file: ./src/handlers/pangolinDispached.ts
    - file: ./src/handlers/karura.ts
    - file: ./src/handlers/kusama.ts
      
    

    
        
