name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:


jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build node
        run: yarn build:node

      - name: Build types
        run: yarn build:types

