name: Release

on:
  push:
    tags:
      - "v*"
  # workflow_dispatch:
  pull_request:


jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup npm token
        uses: dkershner6/use-npm-token-action@v1
        with:
          token: "${{ secrets.NPM_TOKEN }}"
          workspace: /root

      - name: Install deps
        run: |
          apk update
          apk add jq
          yarn install
          npx lerna bootstrap

      - name: Build node
        run: yarn build:node

      - name: Build types
        run: yarn build:types

      - name: Read version
        id: read-version
        run: |
          VERSION=$(cat lerna.json |  jq --raw-output '.version?')
          if [ -z "${VERSION}" ]; then
            echo 'No version found in lerna.json file';
            exit 1
          fi
          echo "::set-output name=VERSION::$VERSION"

      - name: Update version
        run: yarn lernaversion --yes ${{ steps.read-version.outputs.VERSION }}

      - name: Release
        run: yarn build:release


